### ISSUE TITLE
Possible to do a rpi b (rev2.0) hat?

### ISSUE THREAD

**Issue by orrpan** [worlickwerx/pi-parport#13]
If soldering additional pins (p5-pins) would it be possible to use an older rpi, only by changing GPIO ports used and the schematics of the pcb?

http://pi4j.com/pins/model-b-rev2.html

Changing pins like this: 

> 
> 			control_pins: control_pins {
> 				brcm,pins =     <28 29 30 31>;
> 				brcm,function = <1  1 1  1>; // out
> 			};
> 			hd_pin: hd_pin {
> 				brcm,pins =     <7>;
> 				brcm,function = <1>; // out
> 			};
> 			dir_pin: dir_pin {
> 				brcm,pins =     <27>;
> 				brcm,function = <1>; // out
> 			};
> 

Which will leave GPIO14 and GPIO15 free. 

> 				control-gpios = <&gpio 28 1>, // ~nStrobe
> 					        <&gpio 29 1>, // ~nAutoLF
> 					        <&gpio 30 0>, // nInitialize
> 					        <&gpio 31 1>; // ~nSelect
> 				// 74LVC161284 pins in v2 design
> 				hd-gpio = <&gpio 7 0>; // HD
> 				dir-gpio = <&gpio 27 0>; // DIR

**Comment by garlick** [comment]
Yeah, maybe!  Although given that there are several generations of pi now that use the modern GPIO pinout, is it worth the effort?   Then again, most people would say this whole project isn't worth the effort and we should let the parallel port die its natural death, so who am I to talk :-)   Best of luck.

**Comment by garlick** [comment]
Closing as this is probably not worth the effort given that pi foundation has more or less standardized the 40 pin connector for a while now.
