### ISSUE TITLE
clarify hardware license

### ISSUE THREAD

**Issue by garlick** [worlickwerx/pi-parport#23]
The hardware portion of this project was intended to be freely shared and extended.

The project LICENSE is GPL-2.0.  The hardware design I guess would default to GPL-2.0, but that may not be an appropriate license for hardware.  Investigate the state of the practice for "open source hardware" and adopt one of the best practices in this project. 

See: https://www.oshwa.org/definition/

Consider porting the design files from Eagle (proprietary) to KiCAD (free), and silk screening the OSHWA logo on the next version of the board.

**Comment by andersmilton** [comment]
I don't really like GPL for hardware myself. I usually go for CC BY-SA for hardware and GPL for software. But GPL should work.

**Comment by garlick** [comment]
Yeah that might be the way to go.

**Comment by garlick** [comment]
Went with CERN-OHL-1.2
